#!/usr/bin/env bash
# Redirecting
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo echo -e "Ceci n'est pas une page\n" | sudo tee /var/www/html/custom_404.html > /dev/null
sudo sed -i '24i\    location /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\t\t\n}\n\t\terror_page 404             /404.html;\n' /etc/nginx/sites-available/default
#sudo sed -i '/^[^#]*server_name.*;$/a \ \n\tlocation \/redirect_me {\n\t\treturn 301 https://www.linkedin.com/in/abodawoud/;\n\t}' /etc/nginx/sites-available/default
#sudo sed -i '/^[^#]*server_name.*;$/a \ \n\terror_page 404 \/custom_404.html;' /etc/nginx/sites-available/default
sudo service nginx reload
