#!/usr/bin/env bash
# Redirecting
sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo mkdir -p /var/www/abodawoud.tech/html
sudo echo -e "Ceci n'est pas une page\n" | sudo tee /var/www/abodawoud.tech/html/custom_404.html
sudo sed -i '/^[^#]*server_name.*;$/a \ \n\tlocation \/redirect_me {\n\t\treturn 301 https://www.linkedin.com/in/abodawoud/;\n\t}' /etc/nginx/sites-available/default
sudo sed -i '/^[^#]*server_name.*;$/a \ \n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\tinternal;\n\t\troot /var/www/abodawoud.tech/html;\n\t}' /etc/nginx/sites-available/default
sudo service nginx reload
