#!/usr/bin/env bash
# Configure Nginx so that its HTTP response
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo echo -e "Ceci n'est pas une page\n" | sudo tee /var/www/html/custom_404.html > /dev/null
sudo sed -i '/^[^#]*server_name.*;$/a \ \n\tlocation \/redirect_me {\n\t\treturn 301 https://www.linkedin.com/in/abodawoud/;\n\t}' /etc/nginx/sites-available/default
sudo sed -i '/^[^#]*server_name.*;$/a \ \n\terror_page 404 \/custom_404.html;' /etc/nginx/sites-available/default
sudo sed -i '/^[^#]*location \/ {/a \ \n\t\tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx start
sudo nginx -s reload
