#!/usr/bin/env bash
# Bash script that displays:
    # The content of the current directory
    # In a list format
    # Where only the part of the name after the first dash is displayed (refer to the example)

curr_dir=$(pwd)
files=$(ls "$curr_dir")
for file in $files
do
    file_part=$(echo "$file" | cut -d "-" -f 2)
    echo "$file_part"
done
