#!/usr/bin/env bash
# Bash script that gives you information about the school file.
    # The content of the current directory
    # In a list format
    # Where only the part of the name after the first dash is displayed (refer to the example)


if [ -e school ]; then
    echo "school file exists"
    if [ -s school ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -f school ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
